### ISSUE TITLE
Any plan for 0.92.5 release?

### ISSUE THREAD

**Issue by homnath** [textext/pygtk-for-inkscape-windows#1]
I was just curious if you are releasing 0.92.5 any time soon.

**Comment by jcwinkler** [comment]
Hi, you can use the existing packages for 0.92.4 in Inkscape 0.92.5 as well. I just tested it and will update the documentation during this day.

**Comment by homnath** [comment]
Thank you!

**Comment by homnath** [comment]
Thanks so much! I am finally able to run textext with inkscape 0.92.5 as
well. Initially there was a problem but after carefully following
troubleshoot page, I figured that inkscape wasn't on the path. Now it works
like a charm! Amazing extension!

Best,
Hom Nath
